In [1]:
import copy
import os
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from Lib_classes.DataFrameFilesBuilderStack import DataFrameStackBuilder
from Lib_classes.FileArchitecture import PdPickleFileArchitecture
from Lib_classes.funcs import get_max_len_key, get_min_len_key, raise_none
from Lib_classes.Paths import Paths
from Source.Source_aggregate.SourceAggregator import SourceAggregator
from Source.Utils.Signature.BearingFaultSignature import BearingFaultSignature

In [3]:
pfa = PdPickleFileArchitecture.open(os.path.join(Paths.dir_dataframe_pickles, 'Bearing'))
df = pfa.get_file(0)

In [4]:
gen = np.random.default_rng(0)

In [5]:
n_chunks = 10

In [6]:
n_samples_in_chunk = len(df)//n_chunks
n_remains = len(df) - n_samples_in_chunk*n_chunks
n_remains

0

In [7]:
#becouse we have so many intersection of classes
def add_split_columns(df_):
    def reduce(x):
        if np.sum(x) == 0:
            return 0.0
        elif np.sum(x) == 1:
            return np.where(x > 1.0 - 10e-8)[0].item()+1
        elif np.sum(x) == 2:
            variants = np.where(x > 1.0 - 10e-8)[0]
            return float(variants[gen.integers(0, variants.size)])+1
            
    df_['group_index'] = df_[SourceAggregator.REAL_CLASS_ORDER].apply(reduce, axis = 1, raw=True) # type: ignore

    df_['ds_type'] = df_['original_path'].map(lambda x: Path(x).parts[len(Path(Paths.dir_source).absolute().parts)])

In [8]:
add_split_columns(df)
groups = df.groupby(['ds_type', 'group_index'])

In [9]:
map_groups_:dict[str,list] = {}
for key, group_ in groups.groups.items():
    map_groups_[f"{key[0]}_{key[1]}"] = list(group_)

In [10]:
remainders = []
for _ in range(n_remains):
    key = get_max_len_key(map_groups_)
    i = gen.choice(np.arange(len(map_groups_[key])))
    remainders.append(map_groups_[key].pop(i))

remainders

[]

In [11]:
map_chunks = defaultdict(list)
map_groups_remained = copy.deepcopy(map_groups_)
n_group_remains_determined = n_chunks


def split_for_chunks(group_:list, map_chunks_:defaultdict, n_group_remains):
    gen.shuffle(group_)
    need_size = len(group_)//n_chunks
    if need_size == 0:
        p = np.zeros((n_chunks,))
        for key, chunk in map_chunks_.items():
            p[key] = len(chunk)
        p = np.max(p)-p+1
        p = p/np.sum(p)
        
        if n_group_remains > n_group_remains_determined: 
            i_select = gen.choice(
                np.arange(n_chunks),
                size = (len(group_), ),
                p = p,
                replace = False
            )
            
            for chunk in i_select:
                map_chunks_[chunk].append(group_.pop(0))
        else:
            for _ in range(len(group_)):
                get_key = get_min_len_key(map_chunks_)
                map_chunks_[get_key].append(group_.pop())
            
        
    else:
        for chunk in range(n_chunks):
            if need_size != 0:
                current_group = group_[:need_size]
                if len(current_group) != need_size:
                    raise ValueError('len(current_group) != need_size')
                map_chunks_[chunk].extend(group_[:need_size])
                del group_[:need_size]
        
    if len(group_) != 0:
        split_for_chunks(group_, map_chunks_, n_group_remains)


c_groups = len(list(map_groups_.keys()))
for key, group in map_groups_remained.items():
    split_for_chunks(group, map_chunks, c_groups)
    c_groups-=1
    
map_chunks = dict(map_chunks)

In [12]:
map_groups_

{'CWRU_0': [507, 656],
 'CWRU_1': [23, 35, 196, 380, 462, 584, 619, 631, 722, 766, 940],
 'CWRU_2': [71, 76, 207, 216, 451, 464, 484, 517, 670, 805, 998],
 'CWRU_3': [31,
  36,
  60,
  75,
  81,
  164,
  181,
  219,
  365,
  576,
  585,
  660,
  745,
  751,
  764,
  841,
  850,
  856,
  925,
  945,
  985],
 'HUST_0': [253, 948],
 'HUST_2': [14, 544, 991],
 'HUST_3': [151, 303, 510, 526, 888],
 'KAt_0': [24,
  43,
  50,
  86,
  132,
  170,
  183,
  195,
  203,
  224,
  247,
  274,
  292,
  307,
  321,
  339,
  351,
  389,
  390,
  402,
  408,
  410,
  428,
  447,
  452,
  454,
  459,
  496,
  519,
  554,
  568,
  572,
  602,
  612,
  639,
  653,
  663,
  701,
  703,
  712,
  727,
  736,
  738,
  748,
  761,
  771,
  794,
  865,
  893,
  917,
  933,
  936,
  962,
  963],
 'KAt_1': [17,
  28,
  32,
  51,
  56,
  57,
  87,
  89,
  99,
  121,
  124,
  128,
  133,
  136,
  139,
  156,
  165,
  169,
  187,
  191,
  193,
  222,
  225,
  239,
  240,
  241,
  251,
  255,
  269,
  270,
  282,
  289,
  293,
  300,
  310,
  312,
  317,
  327,
  338,
  347,
  353,
  356,
  363,
  367,
  383,
  394,
  399,
  413,
  422,
  438,
  439,
  449,
  461,
  469,
  471,
  476,
  524,
  527,
  574,
  592,
  624,
  676,
  680,
  685,
  688,
  705,
  711,
  730,
  741,
  747,
  752,
  756,
  779,
  782,
  785,
  787,
  812,
  823,
  848,
  852,
  855,
  860,
  878,
  881,
  883,
  895,
  898,
  905,
  913,
  924,
  937,
  941,
  943,
  947,
  961,
  973],
 'KAt_3': [9,
  13,
  20,
  30,
  38,
  61,
  67,
  72,
  74,
  80,
  82,
  107,
  110,
  114,
  126,
  131,
  135,
  140,
  149,
  159,
  162,
  168,
  198,
  204,
  210,
  214,
  258,
  262,
  271,
  272,
  286,
  296,
  306,
  314,
  341,
  345,
  346,
  361,
  392,
  401,
  412,
  425,
  448,
  458,
  465,
  468,
  479,
  488,
  499,
  515,
  518,
  532,
  534,
  541,
  542,
  547,
  550,
  553,
  569,
  571,
  578,
  580,
  583,
  587,
  590,
  617,
  628,
  632,
  635,
  637,
  638,
  640,
  658,
  661,
  665,
  674,
  678,
  687,
  693,
  694,
  704,
  707,
  708,
  717,
  718,
  724,
  728,
  734,
  769,
  781,
  783,
  784,
  788,
  790,
  793,
  804,
  813,
  819,
  828,
  829,
  859,
  892,
  903,
  907,
  921,
  923,
  930,
  935,
  949,
  951,
  960,
  970,
  971,
  978,
  984,
  986,
  990,
  993],
 'MFPT_0': [691],
 'MFPT_1': [513],
 'MFPT_3': [536, 997],
 'Multi-domain_0': [33, 53, 145, 206, 252, 311, 352, 416, 456, 493],
 'Multi-domain_1': [16, 19, 331, 472, 642, 657, 858, 976],
 'Multi-domain_2': [12, 186, 249, 301, 323, 420, 441, 521, 664, 821, 847],
 'Multi-domain_3': [39, 70, 125, 174, 205, 298, 419, 643, 683, 854, 906],
 'Multi-domain2_0': [144,
  278,
  297,
  319,
  324,
  440,
  467,
  478,
  565,
  594,
  682,
  686,
  710,
  796],
 'Multi-domain2_1': [6, 64, 137, 560, 731, 807, 863, 890, 934, 992],
 'Multi-domain2_2': [65, 299, 374, 398, 453, 482, 606, 630, 969],
 'Multi-domain2_3': [48, 68, 115, 279, 370, 407, 654, 672, 689, 754],
 'Multi-domain3_0': [45, 364, 477, 575, 641, 649, 699, 729, 755, 803, 837],
 'Multi-domain3_1': [120, 122, 342, 393, 564, 600, 609, 795, 802, 958],
 'Multi-domain3_2': [55, 184, 291, 340, 415, 601, 626, 644, 760, 809, 843],
 'Multi-domain3_3': [97, 233, 406, 445, 474, 561, 709, 885, 916],
 'SCA_0': [1,
  2,
  3,
  4,
  5,
  8,
  10,
  11,
  15,
  18,
  21,
  26,
  34,
  41,
  44,
  47,
  49,
  52,
  54,
  58,
  59,
  62,
  63,
  66,
  73,
  79,
  85,
  88,
  90,
  91,
  94,
  95,
  96,
  98,
  101,
  102,
  104,
  106,
  108,
  112,
  117,
  118,
  119,
  123,
  127,
  129,
  130,
  138,
  142,
  146,
  147,
  148,
  153,
  157,
  158,
  160,
  171,
  172,
  175,
  176,
  178,
  179,
  185,
  189,
  190,
  194,
  197,
  200,
  208,
  209,
  211,
  213,
  215,
  218,
  223,
  226,
  227,
  228,
  229,
  231,
  234,
  235,
  236,
  242,
  243,
  244,
  245,
  246,
  250,
  254,
  256,
  259,
  261,
  263,
  264,
  265,
  266,
  267,
  268,
  273,
  277,
  283,
  284,
  285,
  287,
  288,
  295,
  308,
  309,
  315,
  316,
  318,
  320,
  322,
  325,
  326,
  328,
  329,
  330,
  332,
  335,
  343,
  344,
  350,
  355,
  358,
  359,
  362,
  368,
  371,
  372,
  375,
  377,
  378,
  381,
  382,
  384,
  386,
  387,
  395,
  396,
  403,
  404,
  405,
  411,
  414,
  421,
  424,
  429,
  431,
  432,
  433,
  434,
  435,
  437,
  442,
  450,
  460,
  463,
  470,
  473,
  480,
  481,
  483,
  486,
  487,
  489,
  490,
  491,
  498,
  500,
  502,
  506,
  508,
  509,
  512,
  514,
  516,
  520,
  523,
  525,
  528,
  529,
  530,
  531,
  533,
  537,
  538,
  543,
  545,
  546,
  548,
  552,
  555,
  556,
  557,
  558,
  559,
  562,
  566,
  567,
  570,
  577,
  579,
  581,
  582,
  588,
  589,
  591,
  593,
  596,
  598,
  599,
  604,
  605,
  607,
  608,
  610,
  611,
  615,
  616,
  620,
  621,
  622,
  623,
  627,
  629,
  633,
  636,
  645,
  646,
  647,
  648,
  650,
  659,
  662,
  666,
  669,
  673,
  675,
  679,
  684,
  690,
  692,
  695,
  696,
  697,
  702,
  713,
  714,
  716,
  719,
  725,
  726,
  732,
  733,
  737,
  740,
  743,
  749,
  753,
  759,
  762,
  763,
  767,
  768,
  770,
  773,
  775,
  776,
  777,
  778,
  780,
  786,
  792,
  797,
  798,
  799,
  801,
  806,
  808,
  811,
  814,
  815,
  816,
  817,
  820,
  824,
  826,
  827,
  830,
  831,
  834,
  835,
  836,
  839,
  840,
  842,
  844,
  846,
  853,
  857,
  867,
  869,
  870,
  871,
  873,
  876,
  877,
  882,
  884,
  886,
  887,
  889,
  891,
  896,
  897,
  901,
  902,
  904,
  909,
  910,
  911,
  912,
  914,
  915,
  919,
  920,
  922,
  927,
  928,
  931,
  932,
  938,
  939,
  942,
  944,
  946,
  950,
  952,
  953,
  955,
  956,
  957,
  968,
  972,
  974,
  975,
  977,
  979,
  980,
  982,
  988,
  995,
  999],
 'SCA_1': [100,
  134,
  141,
  150,
  152,
  177,
  180,
  232,
  290,
  336,
  376,
  397,
  417,
  539,
  586,
  706,
  874,
  959,
  965,
  966,
  967,
  994],
 'SCA_3': [618],
 'Self-built dataset_1': [436, 698],
 'Self-built dataset_3': [455],
 'SpectraQuest MFS dataset_1': [27],
 'SpectraQuest MFS dataset_3': [774],
 'XJTU-SY_0': [29,
  40,
  78,
  109,
  111,
  116,
  155,
  161,
  167,
  173,
  199,
  202,
  217,
  221,
  230,
  257,
  304,
  349,
  366,
  373,
  385,
  427,
  457,
  485,
  501,
  625,
  634,
  651,
  667,
  671,
  720,
  735,
  744,
  746,
  750,
  757,
  800,
  810,
  833,
  838,
  845,
  872,
  879,
  900,
  929,
  983,
  996],
 'XJTU-SY_1': [0,
  25,
  37,
  77,
  83,
  92,
  93,
  103,
  105,
  154,
  163,
  182,
  192,
  201,
  212,
  248,
  260,
  276,
  280,
  337,
  354,
  357,
  360,
  369,
  388,
  391,
  409,
  423,
  492,
  495,
  503,
  505,
  551,
  573,
  597,
  681,
  721,
  739,
  742,
  758,
  765,
  772,
  822,
  825,
  849,
  851,
  861,
  864,
  908,
  954,
  981],
 'XJTU-SY_3': [7,
  22,
  42,
  46,
  69,
  84,
  113,
  143,
  166,
  188,
  220,
  237,
  238,
  275,
  281,
  294,
  302,
  305,
  313,
  333,
  334,
  348,
  379,
  400,
  418,
  426,
  430,
  443,
  444,
  446,
  466,
  475,
  494,
  497,
  504,
  511,
  522,
  535,
  540,
  549,
  563,
  595,
  603,
  613,
  614,
  652,
  655,
  668,
  677,
  700,
  715,
  723,
  789,
  791,
  818,
  832,
  862,
  866,
  868,
  875,
  880,
  894,
  899,
  918,
  926,
  964,
  987,
  989]}

In [13]:
map_groups_remained

{'CWRU_0': [],
 'CWRU_1': [],
 'CWRU_2': [],
 'CWRU_3': [],
 'HUST_0': [],
 'HUST_2': [],
 'HUST_3': [],
 'KAt_0': [],
 'KAt_1': [],
 'KAt_3': [],
 'MFPT_0': [],
 'MFPT_1': [],
 'MFPT_3': [],
 'Multi-domain_0': [],
 'Multi-domain_1': [],
 'Multi-domain_2': [],
 'Multi-domain_3': [],
 'Multi-domain2_0': [],
 'Multi-domain2_1': [],
 'Multi-domain2_2': [],
 'Multi-domain2_3': [],
 'Multi-domain3_0': [],
 'Multi-domain3_1': [],
 'Multi-domain3_2': [],
 'Multi-domain3_3': [],
 'SCA_0': [],
 'SCA_1': [],
 'SCA_3': [],
 'Self-built dataset_1': [],
 'Self-built dataset_3': [],
 'SpectraQuest MFS dataset_1': [],
 'SpectraQuest MFS dataset_3': [],
 'XJTU-SY_0': [],
 'XJTU-SY_1': [],
 'XJTU-SY_3': []}

In [14]:
[f"{key}: {val}" for key, val in  map_chunks.items()]

['7: [507, 23, 216, 841, 60, 86, 50, 292, 274, 712, 898, 56, 461, 422, 883, 353, 438, 624, 156, 128, 813, 638, 341, 126, 272, 718, 583, 553, 114, 892, 678, 694, 691, 997, 145, 858, 249, 683, 278, 6, 279, 649, 802, 809, 885, 189, 620, 344, 608, 846, 543, 1, 798, 659, 362, 974, 245, 871, 396, 487, 995, 759, 460, 901, 820, 236, 538, 581, 662, 719, 836, 350, 123, 94, 244, 226, 325, 972, 867, 523, 102, 150, 539, 455, 116, 161, 385, 427, 929, 182, 409, 503, 83, 495, 987, 549, 866, 42, 511, 333]',
 '1: [656, 619, 805, 985, 585, 14, 510, 183, 771, 428, 454, 865, 852, 924, 469, 191, 937, 17, 338, 741, 187, 547, 903, 214, 262, 580, 935, 784, 661, 921, 790, 728, 53, 821, 906, 467, 144, 934, 482, 689, 364, 393, 340, 233, 525, 889, 839, 508, 811, 775, 108, 287, 405, 877, 690, 176, 375, 98, 725, 434, 223, 516, 753, 148, 629, 876, 915, 514, 328, 403, 91, 153, 79, 621, 288, 489, 817, 227, 147, 716, 932, 397, 965, 27, 651, 757, 373, 810, 597, 551, 212, 391, 93, 772, 989, 305, 522, 677, 563, 595]',
 '0: [196, 998, 219, 660, 31, 544, 132, 738, 568, 519, 459, 241, 878, 356, 905, 752, 685, 782, 812, 787, 860, 617, 783, 30, 346, 704, 769, 72, 159, 271, 788, 532, 412, 311, 331, 847, 174, 297, 710, 863, 606, 370, 699, 342, 55, 916, 243, 213, 266, 902, 952, 509, 891, 650, 582, 767, 104, 235, 326, 381, 209, 130, 359, 481, 999, 588, 830, 556, 506, 62, 3, 44, 763, 498, 579, 372, 2, 593, 673, 919, 157, 967, 100, 774, 221, 349, 983, 750, 360, 423, 276, 721, 0, 715, 832, 918, 880, 446, 723, 238]',
 '2: [380, 451, 164, 365, 253, 303, 496, 247, 612, 402, 748, 193, 779, 165, 28, 705, 943, 270, 317, 756, 139, 499, 693, 401, 162, 107, 392, 550, 149, 210, 971, 984, 140, 416, 441, 125, 682, 807, 65, 407, 477, 795, 626, 561, 646, 470, 968, 816, 636, 566, 545, 52, 944, 308, 834, 5, 623, 737, 988, 909, 537, 218, 927, 773, 870, 277, 259, 178, 615, 695, 322, 295, 529, 645, 928, 808, 127, 955, 421, 957, 874, 959, 180, 501, 40, 304, 78, 230, 103, 864, 201, 248, 492, 113, 964, 668, 275, 540, 655, 426]',
 '3: [584, 484, 76, 81, 850, 572, 170, 653, 351, 736, 408, 89, 347, 87, 225, 895, 383, 251, 169, 471, 67, 168, 734, 640, 534, 628, 80, 286, 204, 665, 515, 819, 493, 976, 664, 323, 298, 319, 890, 630, 654, 803, 600, 644, 97, 329, 622, 284, 942, 208, 696, 377, 530, 146, 231, 197, 424, 776, 979, 450, 570, 268, 831, 555, 486, 437, 15, 815, 200, 386, 557, 920, 768, 54, 10, 591, 806, 610, 982, 792, 417, 141, 336, 746, 744, 257, 217, 366, 861, 765, 357, 681, 369, 700, 418, 69, 504, 899, 789, 926]',
 '4: [631, 517, 764, 576, 991, 526, 224, 893, 936, 203, 410, 973, 711, 524, 300, 363, 881, 848, 785, 282, 465, 951, 306, 361, 131, 542, 674, 632, 978, 448, 859, 993, 33, 16, 420, 39, 594, 686, 992, 299, 115, 575, 564, 415, 445, 254, 211, 264, 411, 96, 41, 85, 95, 58, 320, 647, 546, 842, 826, 473, 911, 158, 138, 343, 869, 857, 666, 171, 786, 66, 384, 914, 596, 616, 726, 882, 605, 256, 355, 378, 706, 232, 618, 155, 900, 199, 109, 667, 849, 25, 981, 822, 742, 652, 400, 443, 7, 497, 188, 894]',
 '5: [462, 670, 945, 925, 151, 24, 307, 321, 390, 389, 394, 961, 57, 676, 99, 310, 293, 133, 51, 239, 970, 74, 923, 61, 637, 717, 458, 793, 587, 781, 590, 536, 206, 19, 301, 205, 796, 64, 969, 48, 45, 958, 601, 406, 922, 577, 88, 528, 980, 777, 490, 835, 404, 179, 318, 432, 285, 215, 8, 263, 956, 387, 228, 814, 684, 599, 129, 229, 265, 382, 749, 502, 904, 435, 827, 950, 172, 531, 552, 59, 376, 994, 436, 29, 457, 202, 173, 720, 280, 92, 77, 758, 851, 444, 220, 281, 791, 613, 430, 313]',
 '6: [35, 940, 207, 751, 745, 888, 602, 917, 639, 554, 43, 794, 327, 947, 574, 222, 136, 121, 289, 32, 688, 479, 687, 296, 9, 658, 635, 986, 960, 708, 804, 724, 110, 456, 642, 521, 70, 440, 731, 453, 754, 837, 122, 184, 474, 512, 395, 607, 142, 743, 797, 309, 887, 669, 90, 886, 604, 117, 692, 896, 714, 939, 799, 733, 562, 11, 589, 840, 912, 267, 34, 273, 977, 246, 26, 463, 897, 598, 702, 975, 290, 152, 698, 996, 167, 634, 838, 879, 154, 505, 354, 739, 260, 22, 603, 535, 294, 475, 494, 466]',
 '8: [722, 464, 181, 75, 948, 701, 339, 452, 195, 447, 727, 941, 855, 680, 747, 730, 399, 527, 476, 439, 913, 930, 13, 468, 569, 345, 488, 578, 82, 38, 541, 829, 707, 252, 657, 12, 854, 419, 478, 137, 398, 68, 641, 120, 843, 291, 844, 106, 480, 175, 558, 648, 483, 190, 567, 953, 491, 21, 315, 118, 185, 520, 431, 283, 946, 335, 778, 910, 194, 242, 250, 732, 780, 931, 873, 770, 884, 49, 4, 633, 762, 134, 177, 671, 833, 485, 800, 625, 337, 908, 388, 825, 163, 818, 875, 46, 614, 237, 143, 348]',
 '9: [766, 71, 36, 856, 761, 963, 962, 703, 663, 933, 124, 592, 413, 823, 449, 312, 255, 240, 367, 269, 518, 425, 828, 198, 314, 907, 135, 949, 571, 258, 20, 990, 513, 352, 472, 186, 643, 324, 565, 560, 374, 672, 729, 755, 609, 760, 709, 429, 533, 112, 358, 368, 119, 332, 679, 73, 675, 500, 801, 18, 47, 442, 713, 261, 160, 548, 330, 433, 611, 414, 559, 740, 371, 63, 938, 697, 316, 234, 101, 627, 853, 824, 966, 586, 111, 735, 872, 845, 37, 105, 954, 573, 192, 166, 84, 379, 302, 334, 862, 868]']

In [15]:
[f"{key}: {len(val)}" for key, val in  map_chunks.items()]

['7: 100',
 '1: 100',
 '0: 100',
 '2: 100',
 '3: 100',
 '4: 100',
 '5: 100',
 '6: 100',
 '8: 100',
 '9: 100']

In [16]:
for i, key in zip(remainders, map_chunks.keys()):
    map_chunks[key].append(i)

In [17]:
[f"{key}: {len(val)}" for key, val in  map_chunks.items()]

['7: 100',
 '1: 100',
 '0: 100',
 '2: 100',
 '3: 100',
 '4: 100',
 '5: 100',
 '6: 100',
 '8: 100',
 '9: 100']

In [18]:
cum_df = None

for key, val in  map_chunks.items():
    new_df = pd.DataFrame(df.iloc[val].groupby(['ds_type', 'group_index']).size(), columns = ['size'])
    if cum_df is None:
        cum_df = new_df
    else:
        cum_df = pd.merge(cum_df, new_df, how = 'outer', on = ['ds_type', 'group_index'], suffixes = ('', f'_{key}'))
cum_df

                                      size  size_1  size_0  size_2  size_3  \
ds_type                  group_index
CWRU                     0             1.0     1.0     NaN     NaN     NaN
                         1             1.0     1.0     1.0     1.0     1.0
                         2             1.0     1.0     1.0     1.0     2.0
                         3             2.0     2.0     3.0     2.0     2.0
HUST                     0             NaN     NaN     NaN     1.0     NaN
                         2             NaN     1.0     1.0     NaN     NaN
                         3             NaN     1.0     NaN     1.0     NaN
KAt                      0             5.0     5.0     5.0     5.0     6.0
                         1            10.0     9.0    10.0    10.0     9.0
                         3            12.0    11.0    12.0    12.0    12.0
MFPT                     0             1.0     NaN     NaN     NaN     NaN
                         1             NaN     NaN     NaN     NaN     NaN
                         3             1.0     NaN     NaN     NaN     NaN
Multi-domain             0             1.0     1.0     1.0     1.0     1.0
                         1             1.0     NaN     1.0     NaN     1.0
                         2             1.0     1.0     1.0     1.0     2.0
                         3             1.0     1.0     1.0     1.0     1.0
Multi-domain2            0             1.0     2.0     2.0     1.0     1.0
                         1             1.0     1.0     1.0     1.0     1.0
                         2             NaN     1.0     1.0     1.0     1.0
                         3             1.0     1.0     1.0     1.0     1.0
Multi-domain3            0             1.0     1.0     1.0     1.0     1.0
                         1             1.0     1.0     1.0     1.0     1.0
                         2             1.0     1.0     1.0     1.0     1.0
                         3             1.0     1.0     1.0     1.0     1.0
SCA                      0            36.0    37.0    35.0    36.0    35.0
                         1             2.0     2.0     2.0     3.0     3.0
                         3             NaN     NaN     NaN     NaN     NaN
Self-built dataset       1             NaN     NaN     NaN     NaN     NaN
                         3             1.0     NaN     NaN     NaN     NaN
SpectraQuest MFS dataset 1             NaN     1.0     NaN     NaN     NaN
                         3             NaN     NaN     1.0     NaN     NaN
XJTU-SY                  0             5.0     4.0     4.0     5.0     5.0
                         1             5.0     6.0     5.0     5.0     5.0
                         3             6.0     6.0     7.0     7.0     7.0

                                      size_4  size_5  size_6  size_8  size_9
ds_type                  group_index
CWRU                     0               NaN     NaN     NaN     NaN     NaN
                         1               1.0     1.0     2.0     1.0     1.0
                         2               1.0     1.0     1.0     1.0     1.0
                         3               2.0     2.0     2.0     2.0     2.0
HUST                     0               NaN     NaN     NaN     1.0     NaN
                         2               1.0     NaN     NaN     NaN     NaN
                         3               1.0     1.0     1.0     NaN     NaN
KAt                      0               5.0     5.0     6.0     6.0     6.0
                         1               9.0    10.0     9.0    10.0    10.0
                         3              12.0    11.0    12.0    12.0    12.0
MFPT                     0               NaN     NaN     NaN     NaN     NaN
                         1               NaN     NaN     NaN     NaN     1.0
                         3               NaN     1.0     NaN     NaN     NaN
Multi-domain             0               1.0     1.0     1.0     1.0     1.0
                         1               1.0     1.0     1.0     1.0     1.0
                         2               1.0     1.0     1.0     1.0     1.0
                         3               1.0     1.0     1.0     2.0     1.0
Multi-domain2            0               2.0     1.0     1.0     1.0     2.0
                         1               1.0     1.0     1.0     1.0     1.0
                         2               1.0     1.0     1.0     1.0     1.0
                         3               1.0     1.0     1.0     1.0     1.0
Multi-domain3            0               1.0     1.0     1.0     1.0     2.0
                         1               1.0     1.0     1.0     1.0     1.0
                         2               1.0     1.0     1.0     2.0     1.0
                         3               1.0     1.0     1.0     NaN     1.0
SCA                      0              35.0    36.0    35.0    35.0    35.0
                         1               2.0     2.0     2.0     2.0     2.0
                         3               1.0     NaN     NaN     NaN     NaN
Self-built dataset       1               NaN     1.0     1.0     NaN     NaN
                         3               NaN     NaN     NaN     NaN     NaN
SpectraQuest MFS dataset 1               NaN     NaN     NaN     NaN     NaN
                         3               NaN     NaN     NaN     NaN     NaN
XJTU-SY                  0               5.0     5.0     5.0     5.0     4.0
                         1               5.0     5.0     5.0     5.0     5.0
                         3               7.0     7.0     7.0     7.0     7.0

In [19]:
class EqualSizeSplitter:
    """
    Pure Fabrication responsible for splitting a dataset of indices into
    exactly N chunks of equal size, maintaining stratification.
    """
    def __init__(self,  rng: np.random.Generator, n_chunks: Optional[int] = None, size_chunk: Optional[int] = None, size: Optional[int] = None):
        self._rng = rng
        if size_chunk is not None and size is not None:
            self.n_chunks = size//size_chunk
            self.max_size_chunk = size_chunk
        elif n_chunks is not None:
            self.n_chunks = n_chunks
        self._n_group_remains_determined = self.n_chunks

    def split(self, groups: Dict[str, List[int]]) -> Dict[int, List[int]]:
        """
        Distributes indices from groups into chunks.
        
        1. Trims global excess to ensure total_size % n_chunks == 0.
        2. Distributes main body of groups evenly.
        3. Distributes remainders probabilistically to balance chunk sizes.
        """
        # Create a working copy to avoid side effects
        working_groups = {k: v.copy() for k, v in groups.items()}
        
        tail_idx = self._trim_global_excess(working_groups)
        
        chunks = defaultdict(list)
        
        # Sort keys to ensure deterministic processing order
        sorted_keys = sorted(working_groups.keys())
        c_working_groups = len(working_groups)
        for key in sorted_keys:
            indices = working_groups[key]
            self._rng.shuffle(indices)
            
            self._split_group(indices, chunks, c_working_groups)
            c_working_groups-=1
        
        chunks[max(chunks.keys())+1] = tail_idx
        for key, val in chunks.items():
            chunks[key] = self._rng.permutation(val).tolist()
        
        return dict(chunks)

    def _trim_global_excess(self, groups: Dict[str, List[int]]) -> list:
        """Removes indices from largest groups so total count fits n_chunks."""
        tail_idx = []
        total_samples = sum(len(v) for v in groups.values())
        if hasattr(self, 'max_size_chunk'):
            remainder = total_samples % self.max_size_chunk
        else:
            remainder = total_samples % self.n_chunks
        
        if remainder == 0:
            return []

        # Strategy: Remove from the largest groups to preserve rare classes
        for _ in range(remainder):
            largest_group_key = max(groups, key=lambda k: len(groups[k]))
            if groups[largest_group_key]:
                # Remove a random element
                idx_to_remove = self._rng.integers(0, len(groups[largest_group_key]))
                tail_idx.append(groups[largest_group_key].pop(idx_to_remove))
                
        return tail_idx

    def _split_group(self, indices: List[int], chunks: Dict[int, List[int]], n_group_remains:int) -> None:
        """Splits a single group's indices across chunks."""
        need_size = len(indices)//self.n_chunks
        if need_size == 0:
            self._split_underloaded_chunk(indices, chunks, n_group_remains)
        else:
            for chunk in range(self.n_chunks):
                if need_size != 0:
                    current_group = indices[:need_size]
                    if len(current_group) != need_size:
                        raise ValueError('len(current_group) != need_size')
                    chunks[chunk].extend(indices[:need_size])
                    del indices[:need_size]
        
        if len(indices) != 0:
            self._split_group(indices, chunks, n_group_remains)

    def _split_underloaded_chunk(self, indices: List[int], chunks: Dict[int, List[int]], n_group_remains:int ):
        """
        Selects a chunk index based on inverse probability of current size.
        Smaller chunks have higher probability of being selected.
        """
        p = np.zeros((self.n_chunks,))
        for key, chunk in chunks.items():
            p[key] = len(chunk)
        p = np.max(p)-p+1
        p = p/np.sum(p)
        
        if n_group_remains > self._n_group_remains_determined: 
            i_select = gen.choice(
                np.arange(self.n_chunks),
                size = (len(indices), ),
                p = p,
                replace = False
            )
            
            for chunk in i_select:
                chunks[chunk].append(indices.pop(0))
        else:
            for _ in range(len(indices)):
                get_key = min(chunks.keys(), key=lambda k: len(chunks[k]))
                chunks[get_key].append(indices.pop())
         


class BalancedChunkRunner:
    """
    Controller responsible for loading data and coordinating the split.
    """
    def __init__(self, 
                 pfa: PdPickleFileArchitecture,
                 spliter: EqualSizeSplitter,
                 signature_strategy: StratificationSignature,
                 rng: np.random.Generator
        ):
        self.pfa = pfa
        
        # Composition of helper classes
        self._signature_strategy = signature_strategy
        self._splitter = spliter
        self._rng = rng

    def generate_chunk_indices(self) -> Dict[int, List[int]]:
        """
        Loads a file, groups data by signature, and returns balanced chunk indices.
        """
        cum_groups = defaultdict(list)
        for i in self.pfa.iter_stack_index():
            df = self.pfa.get_file(i)
            groups = self._group_data(df, i)
            [cum_groups[k].extend(v) for k, v in groups.items()]
            
        chunk_map = self._splitter.split(groups)
        
        return chunk_map
    
    def provide_chunks(self, chunks:dict):
        for key, chunk in chunks.items():
            chunk_df = None
            for i in self.pfa.iter_stack_index():
                cur_chunks = list(map(lambda x: x[1], filter(lambda x: x[0] == i, chunk)))
                df = self.pfa.get_file(i).iloc[cur_chunks]
                chunk_df = pd.concat([chunk_df, df], ignore_index=True) if chunk_df is not None else df
            chunk_df = raise_none(chunk_df).sample(frac=1, random_state=self._rng.integers(0, np.iinfo(np.int32).max)).reset_index(drop=True)
            yield key, chunk_df
                    
            
            
            

    def _group_data(self, df: pd.DataFrame, c_file:int) -> Dict[str, List[int]]:
        """Groups DataFrame indices by their stratification signature."""
        groups = defaultdict(list)
        
        for idx, row in df.iterrows():
            signature = self._signature_strategy.get_signature(row)
            groups[signature].append((c_file, idx))
        return dict(groups)

NameError: name 'StratificationSignature' is not defined

In [ ]:
rng = np.random.default_rng(0)
bcr = BalancedChunkRunner(
    pfa,
    EqualSizeSplitter(rng, n_chunks = 10),
    BearingFaultSignature(SourceAggregator.REAL_CLASS_ORDER, rng),
    rng
)
chunks = bcr.generate_chunk_indices()

In [ ]:
len(pfa.rows())

8843

In [ ]:
[f"{key}: {len(val)}" for key, val in  chunks.items()]

['0: 884',
 '1: 884',
 '2: 884',
 '3: 884',
 '4: 884',
 '5: 884',
 '6: 884',
 '7: 884',
 '8: 884',
 '9: 884',
 '10: 3']

In [ ]:
cum_df = None

for key, val in  chunks.items():
    # print(key, val)
    new_df = pd.DataFrame(df.iloc[list(map(lambda x: x[1], val))].groupby(['ds_type', 'group_index']).size(), columns = ['size'])
    if cum_df is None:
        cum_df = new_df
    else:
        cum_df = pd.merge(cum_df, new_df, how = 'outer', on = ['ds_type', 'group_index'], suffixes = ('', f'_{key}'))
cum_df

                                       size  size_1  size_2  size_3  size_4  \
ds_type                  group_index
CWRU                     0              1.0     1.0     1.0     1.0     1.0
                         1             11.0    10.0    10.0    11.0    11.0
                         2             10.0    10.0    10.0    10.0    10.0
                         3             20.0    20.0    21.0    20.0    20.0
HUST                     0              1.0     1.0     2.0     1.0     1.0
                         1              3.0     3.0     2.0     3.0     3.0
                         2              3.0     3.0     3.0     3.0     2.0
                         3              3.0     4.0     3.0     3.0     3.0
JNU                      0              NaN     1.0     NaN     NaN     1.0
                         1              1.0     NaN     NaN     NaN     NaN
                         2              NaN     NaN     1.0     1.0     NaN
                         3              NaN     1.0     NaN     NaN     1.0
MFPT                     0              NaN     NaN     1.0     NaN     NaN
                         1              1.0     NaN     NaN     NaN     1.0
                         3              1.0     1.0     1.0     1.0     1.0
Multi-domain             0             10.0     9.0    10.0    10.0    10.0
                         1             10.0    10.0    10.0     9.0    10.0
                         2             10.0    10.0    10.0     9.0    10.0
                         3             10.0    10.0     9.0    10.0     9.0
Multi-domain2            0             10.0     9.0    10.0    10.0    10.0
                         1             10.0    10.0     9.0     9.0     9.0
                         2              9.0     9.0    10.0     9.0    10.0
                         3              9.0     9.0     9.0    10.0    10.0
Multi-domain3            0              9.0     9.0    10.0    10.0    10.0
                         1             10.0    10.0     9.0    10.0     9.0
                         2              9.0    10.0    10.0     9.0     9.0
                         3              9.0     9.0     9.0    10.0     9.0
SCA                      0            482.0   481.0   481.0   482.0   481.0
                         1             34.0    35.0    35.0    35.0    35.0
                         2              2.0     2.0     2.0     2.0     2.0
                         3             25.0    25.0    25.0    24.0    25.0
Self-built dataset       1              1.0     1.0     1.0     1.0     1.0
                         2              1.0     NaN     NaN     NaN     1.0
                         3              NaN     2.0     1.0     2.0     NaN
SpectraQuest MFS dataset 1              1.0     1.0     1.0     1.0     1.0
                         2              1.0     1.0     NaN     NaN     NaN
                         3              1.0     NaN     1.0     1.0     1.0
XJTU-SY                  0             40.0    41.0    41.0    41.0    41.0
                         1             52.0    52.0    52.0    51.0    51.0
                         3             63.0    63.0    63.0    64.0    64.0
fm6xzxnf36-2             0              1.0     1.0     NaN     NaN     NaN
                         1              5.0     5.0     6.0     6.0     6.0
                         3              5.0     5.0     5.0     5.0     5.0

                                      size_5  size_6  size_7  size_8  size_9  \
ds_type                  group_index
CWRU                     0               1.0     1.0     1.0     1.0     1.0
                         1              10.0    10.0    10.0    10.0    10.0
                         2              10.0    10.0    10.0    10.0    10.0
                         3              20.0    20.0    21.0    20.0    21.0
HUST                     0               2.0     1.0     2.0     2.0     2.0
                         1               2.0     2.0     2.0     2.0     2.0
                         2               3.0     3.0     2.0     3.0     3.0
                         3               3.0     3.0     4.0     3.0     3.0
JNU                      0               NaN     NaN     NaN     NaN     1.0
                         1               NaN     1.0     1.0     NaN     NaN
                         2               1.0     NaN     NaN     NaN     NaN
                         3               NaN     1.0     NaN     NaN     NaN
MFPT                     0               1.0     NaN     NaN     NaN     1.0
                         1               1.0     1.0     1.0     1.0     1.0
                         3               1.0     1.0     1.0     1.0     1.0
Multi-domain             0               9.0     9.0     9.0    10.0    10.0
                         1              10.0     9.0    10.0     9.0     9.0
                         2               9.0     9.0    10.0    10.0     9.0
                         3              10.0     9.0    10.0     9.0    10.0
Multi-domain2            0               9.0     9.0    10.0     9.0    10.0
                         1              10.0    10.0    10.0    10.0     9.0
                         2              10.0    10.0    10.0    10.0     9.0
                         3              10.0    10.0     9.0    10.0    10.0
Multi-domain3            0               9.0    10.0     9.0    10.0     9.0
                         1               9.0    10.0     9.0    10.0    10.0
                         2              10.0    10.0     9.0    10.0     9.0
                         3               9.0    10.0    10.0    10.0    10.0
SCA                      0             482.0   482.0   481.0   482.0   481.0
                         1              35.0    35.0    34.0    34.0    34.0
                         2               2.0     2.0     3.0     3.0     3.0
                         3              25.0    25.0    25.0    25.0    25.0
Self-built dataset       1               1.0     1.0     1.0     NaN     1.0
                         2               NaN     1.0     NaN     NaN     NaN
                         3               1.0     NaN     1.0     1.0     1.0
SpectraQuest MFS dataset 1               1.0     1.0     1.0     1.0     NaN
                         2               NaN     NaN     NaN     NaN     1.0
                         3               1.0     1.0     1.0     1.0     1.0
XJTU-SY                  0              41.0    41.0    41.0    41.0    41.0
                         1              51.0    51.0    51.0    51.0    51.0
                         3              64.0    63.0    63.0    63.0    63.0
fm6xzxnf36-2             0               NaN     1.0     1.0     1.0     1.0
                         1               6.0     5.0     5.0     5.0     5.0
                         3               5.0     6.0     6.0     6.0     6.0

                                      size_10
ds_type                  group_index
CWRU                     0                NaN
                         1                NaN
                         2                NaN
                         3                NaN
HUST                     0                NaN
                         1                NaN
                         2                NaN
                         3                NaN
JNU                      0                NaN
                         1                NaN
                         2                NaN
                         3                NaN
MFPT                     0                NaN
                         1                NaN
                         3                NaN
Multi-domain             0                NaN
                         1                NaN
                         2                NaN
                         3                NaN
Multi-domain2            0                NaN
                         1                NaN
                         2                NaN
                         3                NaN
Multi-domain3            0                NaN
                         1                NaN
                         2                NaN
                         3                NaN
SCA                      0                3.0
                         1                NaN
                         2                NaN
                         3                NaN
Self-built dataset       1                NaN
                         2                NaN
                         3                NaN
SpectraQuest MFS dataset 1                NaN
                         2                NaN
                         3                NaN
XJTU-SY                  0                NaN
                         1                NaN
                         3                NaN
fm6xzxnf36-2             0                NaN
                         1                NaN
                         3                NaN

In [ ]:


FOLDER_NAME = 'balancer_chunks'
path = os.path.join(Paths.dir_dataframe_pickles, 'Bearing', FOLDER_NAME)

In [ ]:
pmf = DataFrameStackBuilder(
    list(pfa.get_columns()), 
    PdPickleFileArchitecture(
        path,
        max_stack_size=len(next(iter(chunks.values())))
    )
)

for k_, df in bcr.provide_chunks(chunks):
    pmf.add_df(df)

pmf.save_tail()

In [ ]:
pfa_chunks = PdPickleFileArchitecture.open(path)

In [ ]:
cum_df = None

for i in pfa_chunks.iter_stack_index():
    df = pfa_chunks.get_file(i)
    add_split_columns(df)
    new_df = pd.DataFrame(df.groupby(['ds_type', 'group_index']).size(), columns = ['size'])
    if cum_df is None:
        cum_df = new_df
    else:
        print(i)
        cum_df = pd.merge(cum_df, new_df, how = 'outer', on = ['ds_type', 'group_index'], suffixes = ('', f'_{i}'))
cum_df

1
2
3
4
5
6
7
8
9
10

                                       size  size_1  size_2  size_3  size_4  \
ds_type                  group_index
CWRU                     0.0            1.0     1.0     1.0     1.0     1.0
                         1.0           10.0    10.0    10.0    10.0    10.0
                         2.0           10.0    10.0    10.0    10.0    10.0
                         3.0           20.0    20.0    20.0    20.0    21.0
HUST                     0.0            1.0     2.0     2.0     1.0     1.0
                         1.0            4.0     2.0     3.0     3.0     3.0
                         2.0            2.0     1.0     4.0     2.0     3.0
                         3.0            3.0     6.0     1.0     3.0     3.0
JNU                      0.0            NaN     NaN     1.0     NaN     NaN
                         1.0            NaN     NaN     NaN     NaN     1.0
                         2.0            1.0     NaN     1.0     1.0     NaN
                         3.0            NaN     NaN     NaN     1.0     NaN
MFPT                     0.0            NaN     1.0     NaN     1.0     NaN
                         1.0            1.0     1.0     1.0     NaN     1.0
                         3.0            1.0     1.0     1.0     1.0     1.0
Multi-domain             0.0           10.0    10.0     9.0    10.0     9.0
                         1.0           10.0     9.0    10.0     9.0    10.0
                         2.0           10.0     9.0     9.0    10.0     9.0
                         3.0            9.0     9.0     9.0    10.0    10.0
Multi-domain2            0.0            9.0     9.0    10.0    10.0    10.0
                         1.0           10.0    10.0    10.0     9.0     9.0
                         2.0            9.0    10.0     9.0    10.0    10.0
                         3.0           10.0    10.0    10.0    10.0     9.0
Multi-domain3            0.0            9.0    10.0    10.0    10.0     9.0
                         1.0           10.0     9.0    10.0     9.0    10.0
                         2.0           10.0     9.0     9.0    10.0    10.0
                         3.0            9.0    10.0     9.0     9.0    10.0
SCA                      0.0          482.0   482.0   482.0   481.0   481.0
                         1.0           35.0    35.0    35.0    35.0    34.0
                         2.0            2.0     2.0     2.0     2.0     3.0
                         3.0           24.0    25.0    25.0    25.0    25.0
Self-built dataset       1.0            1.0     1.0     1.0     1.0     1.0
                         2.0            1.0     NaN     1.0     NaN     NaN
                         3.0            1.0     1.0     NaN     1.0     1.0
SpectraQuest MFS dataset 1.0            1.0     1.0     1.0     1.0     1.0
                         2.0            1.0     1.0     NaN     NaN     NaN
                         3.0            1.0     NaN     1.0     1.0     1.0
XJTU-SY                  0.0           40.0    41.0    41.0    41.0    41.0
                         1.0           53.0    52.0    51.0    53.0    52.0
                         3.0           62.0    63.0    64.0    62.0    63.0
fm6xzxnf36-2             0.0            1.0     1.0     NaN     NaN     NaN
                         1.0            5.0     5.0     6.0     6.0     6.0
                         3.0            5.0     5.0     5.0     5.0     5.0

                                      size_5  size_6  size_7  size_8  size_9  \
ds_type                  group_index
CWRU                     0.0             1.0     1.0     1.0     1.0     1.0
                         1.0            11.0    10.0    11.0    10.0    11.0
                         2.0            10.0    10.0    10.0    10.0    10.0
                         3.0            21.0    21.0    20.0    20.0    20.0
HUST                     0.0             1.0     2.0     2.0     2.0     1.0
                         1.0             2.0     3.0     2.0     1.0     5.0
                         2.0             2.0     1.0     4.0     3.0     4.0
                         3.0             3.0     5.0     2.0     4.0     NaN
JNU                      0.0             NaN     1.0     1.0     NaN     NaN
                         1.0             1.0     NaN     NaN     NaN     1.0
                         2.0             NaN     NaN     NaN     NaN     NaN
                         3.0             NaN     1.0     NaN     1.0     NaN
MFPT                     0.0             NaN     NaN     NaN     NaN     1.0
                         1.0             1.0     NaN     1.0     1.0     NaN
                         3.0             1.0     1.0     1.0     1.0     1.0
Multi-domain             0.0            10.0     9.0    10.0     9.0    10.0
                         1.0            10.0    10.0    10.0     9.0     9.0
                         2.0            10.0    10.0    10.0     9.0    10.0
                         3.0            10.0     9.0    10.0    10.0    10.0
Multi-domain2            0.0            10.0    10.0     9.0    10.0     9.0
                         1.0            10.0     9.0    10.0     9.0    10.0
                         2.0            10.0     9.0     9.0    10.0    10.0
                         3.0             9.0     9.0     9.0    10.0    10.0
Multi-domain3            0.0             9.0    10.0    10.0     9.0     9.0
                         1.0            10.0     9.0    10.0    10.0     9.0
                         2.0             9.0    10.0     9.0    10.0     9.0
                         3.0             9.0    10.0     9.0    10.0    10.0
SCA                      0.0           482.0   482.0   481.0   481.0   481.0
                         1.0            34.0    34.0    34.0    35.0    35.0
                         2.0             2.0     2.0     3.0     3.0     2.0
                         3.0            25.0    25.0    25.0    25.0    25.0
Self-built dataset       1.0             1.0     1.0     1.0     1.0     NaN
                         2.0             NaN     NaN     NaN     1.0     NaN
                         3.0             1.0     1.0     1.0     NaN     2.0
SpectraQuest MFS dataset 1.0             1.0     1.0     1.0     1.0     NaN
                         2.0             NaN     NaN     NaN     NaN     1.0
                         3.0             1.0     1.0     1.0     1.0     1.0
XJTU-SY                  0.0            41.0    41.0    41.0    41.0    41.0
                         1.0            52.0    53.0    51.0    51.0    52.0
                         3.0            63.0    61.0    63.0    63.0    62.0
fm6xzxnf36-2             0.0             NaN     1.0     1.0     1.0     1.0
                         1.0             6.0     5.0     5.0     5.0     5.0
                         3.0             5.0     6.0     6.0     6.0     6.0

                                      size_10
ds_type                  group_index
CWRU                     0.0              NaN
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
HUST                     0.0              NaN
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
JNU                      0.0              NaN
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
MFPT                     0.0              NaN
                         1.0              NaN
                         3.0              NaN
Multi-domain             0.0              NaN
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
Multi-domain2            0.0              NaN
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
Multi-domain3            0.0              NaN
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
SCA                      0.0              3.0
                         1.0              NaN
                         2.0              NaN
                         3.0              NaN
Self-built dataset       1.0              NaN
                         2.0              NaN
                         3.0              NaN
SpectraQuest MFS dataset 1.0              NaN
                         2.0              NaN
                         3.0              NaN
XJTU-SY                  0.0              NaN
                         1.0              NaN
                         3.0              NaN
fm6xzxnf36-2             0.0              NaN
                         1.0              NaN
                         3.0              NaN

In [ ]:
SourceAggregator.split_chunks(10)

Using cuda:0 device

11it [01:34,  8.62s/it]